### ISSUE TITLE
Feature Request: Hide inactive Budgets on Budgets Tab.

### ISSUE THREAD

**Issue by DavidOliMar** [victorbalssa/abacus#158]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Would it be possible that when accessing the budgets tab, the budgets that are marked in the App as NOT Active do not appear?

I have several non-active ones that I don't want to delete because they contain data but they dirty the View of budget tabs.

_As Sn0wed1 has said, this would be a good option if possible._

**As a user I would like the ability to hide inactive budgets from the budget tab view.**

Thank you very much for your work with the App. I use it every day ; )

**Comment by victorbalssa** [comment]
Thank you @DavidOliMar!
Can you recreate this issue in English please? it will be helpful for everyone to follow, search, request in English so everyone can understand.

**Comment by Sn0wed1** [comment]
_Loose Translation:_

**Is your feature request related to a problem? Please describe.**

 I have several inactive budgets that clutter the budget tab view. 

**Describe the solution you'd like**

As a user I would like the ability to hide inactive budgets from the budget tab view.

**Describe alternatives you've considered**

N/A

**Additional context**

I don't want to delete these budgets because they contain data.

_Explicit Translation:_

Thank you very much for your work with the App. I use it daily;)

**Comment by DavidOliMar** [comment]
> Thank you @DavidOliMar!
> 
> Can you recreate this issue in English please? it will be helpful for everyone to follow, search, request in English so everyone can understand.
> 
> 

Sorry for putting the text in Spanish. It's the first time I've written to a Git. 

I'm going to edit the text and put it in English
