### ISSUE TITLE
Feature Request: Push notification

### ISSUE THREAD

**Issue by mrahmadt** [victorbalssa/abacus#276]
Is it possible to push notifications to the App

I'm running different scripts in the backend for example to detect abnormal transactions, sms to transactions, subscription detection, expense analysis 

Currently these scripts runs and send details to telegram

It would be an amazing to actually just send the notification to Abacus

**Comment by victorbalssa** [comment]
Thanks @mrahmadt, I'll do some research.

**Comment by andyslucky** [comment]
A couple points... 
- Regardless of what technology is used for push notifications, data security will be a concern (notifications for an application have to go through either an Apple or Google service to be delivered to the device). This may jeopardize the head line of the abacus app being "No external API calls nor Analytics API, not even sentry / crashlytics.".
- Since Firefly does not have much built in regarding push notifications (other than email), another service would most likely need to be created to serve this purpose designed to integrate well with abacus. Since Firefly is typically self-hosted by tech-savy individuals, a service that asks more of the "user" in way of setup/management might not be out of the question (quicker prototype); is there an appetite for a hands-off "Just tell me about my finances!" approach? That might take some more time.
- Some worthwhile mentions that may satisfy your requirements in the meantime:
There are existing services with the sole purpose of push notifications (though they will go to a separate app instead of abacus) which might provide this functionality until abacus can integrate this functionality
  - https://ntfy.sh/
  - https://gotify.net/

**Comment by victorbalssa** [comment]
@mrahmadt, @andyslucky,
I'm closing this issue to focus on the mobile application client side rather than trying to get FIII updated to support sending push notification.
