### ISSUE TITLE
Bug: Cannot delete credentials

### ISSUE THREAD

**Issue by quark-works** [victorbalssa/abacus#305]
**Describe the bug**
On the credentials screen, using the "Edit" function and trying to delete store credentials doesn't work.
Additionally, there's no option to remove credentials from the configuration, only on app startup.

**To Reproduce**
1. Start the app. Shows the Credentials screen.
2. Click on Edit
3. Try to remove a credential.
4. Pick "Delete" when asked "Are you sure2
5. Nothing happens

**Expected behavior**
Credential should be deleted.

**Smartphone (please complete the following information):**
 - Device: iPhone 13
 - OS: iOS 17.5.1
 - Version 0.16.0

**Comment by hamza-fadil** [comment]
Hi Victor, I believe I have a fix that could solve the issue in my branch : https://github.com/victorbalssa/abacus/compare/develop...hamza-fadil:abacus:hfadil/cleanup
I didn't have the time to try it thoroughly due to lack of time lately
It's mainly due to an issue with piggybanks not being reset correctly
I'll open the PR; was planning to include it with a new feature
